增加了量化脚本，swift和xinference的推理readme，在readme中增加了常用模块和新模块的快速导航
OpenBMB/MiniCPM-V pull request #334
Opened 2024-07-12 08:12 UTC by LDLINGLINGLING

2024-07-18 03:19 UTC, yiranyyu requested changes
* Typos shall be fixed before merging (such as `finetuen`).
* First letter should be capital in table titles (such as `inference => Inference` and `quantize` => `Quantization`
* Terminology names shall follow common usage (such as `LoRA` and `Gradio`)
* Section descriptions are required.
* Section titles should follow the format of existing titles, including documents in docs/ folder.
*

2024-07-18 07:35 UTC, LDLINGLINGLING commented
非常感谢，已经按照要求修改，如果还有哪里不对，请您指出

2024-07-19 09:20 UTC, yiranyyu requested changes
* Specialized terms like LoRA, SWIFT and APK should follow the origin cases (rather than lora or Lora)
* Such two navigation tables still lacks description in their sections.
* Usage of indentation in code blocks in markdown files should be consistent (such as when do we need a tab for leading spaces).

2024-07-23 07:15 UTC, LDLINGLINGLING commented
按照要求做了修改，其中apk的专业术语没有修改，这是因为apk在之前的readme中都是小写英文，因此沿用了原来的表述方式

2024-07-25 06:49 UTC, yiranyyu requested changes
* README.md and README_zh.md should be consistent. I found mismatches in the navigation table.

Other contents seems to be fine for now.

2024-07-26 02:13 UTC, LDLINGLINGLING commented
Ensure that there is no difference between the readme_zh and the readme navigation bar in new commit
.

2024-07-30 05:56 UTC, iceflame89 requested changes

2024-07-30 05:56 UTC, iceflame89 commented on docs/swift_train_and_infer.md
> +model_id_or_path # 可以写huggingface的模型id或者本地模型地址
建议将注释改都成英文

2024-07-30 05:56 UTC, iceflame89 commented on quantize/bnb_quantize.py
> +# 创建一个配置对象来指定量化参数
注释改成英文

2024-07-30 05:56 UTC, iceflame89 commented on quantize/bnb_quantize.py
> +print('量化后输出',response)
print改成英文

2024-07-30 05:56 UTC, iceflame89 commented on quantize/bnb_quantize.py
> +device = 'cuda' if torch.cuda.is_available() else 'cpu'
BitsAndBytes 支持cpu吗？

2024-07-30 06:16 UTC, LDLINGLINGLING commented on quantize/bnb_quantize.py
> +device = 'cuda' if torch.cuda.is_available() else 'cpu'
这里确实有问题，支持量化，但是不支持推理

2024-07-30 06:38 UTC, LDLINGLINGLING commented on docs/swift_train_and_infer.md
> +model_id_or_path # 可以写huggingface的模型id或者本地模型地址
已经修改

2024-07-30 06:38 UTC, LDLINGLINGLING commented on quantize/bnb_quantize.py
> +# 创建一个配置对象来指定量化参数
已经修改

2024-07-30 06:38 UTC, LDLINGLINGLING commented on quantize/bnb_quantize.py
> +print('量化后输出',response)
已经修改

2024-07-30 06:52 UTC, iceflame89 approved these changes

2024-07-30 22:59 UTC, merged